### ISSUE TITLE
Build fails on odd vfsStream related issue

### ISSUE THREAD

**Issue by johnknl** [kleijnweb/symfony-swagger-microservice-edition#1]
swagger-bundle tests pass with pretty much the same code. Needs further investigation.

```
[2015-09-06 20:09:47] app.CRITICAL: Runtime error [logref 55ec9d8bbb172]: exception 'InvalidArgumentException' with message 'Document file '../web/petstore.yml' does not exist'' in /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/kleijnweb/swagger-bundle/src/Document/SwaggerDocument.php:36 Stack trace: #0 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/kleijnweb/swagger-bundle/src/Document/DocumentRepository.php(31): KleijnWeb\SwaggerBundle\Document\SwaggerDocument->__construct('../web/petstore...') #1 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/kleijnweb/swagger-bundle/src/Routing/SwaggerRouteLoader.php(55): KleijnWeb\SwaggerBundle\Document\DocumentRepository->get('../web/petstore...') #2 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/config/Loader/FileLoader.php(112): KleijnWeb\SwaggerBundle\Routing\SwaggerRouteLoader->load('../web/petstore...', 'swagger') #3 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/routing/Loader/YamlFileLoader.php(175): Symfony\Component\Config\Loader\FileLoader->import('../web/petstore...', 'swagger', false, '/home/travis/bu...') #4 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/routing/Loader/YamlFileLoader.php(93): Symfony\Component\Routing\Loader\YamlFileLoader->parseImport(Object(Symfony\Component\Routing\RouteCollection), Array, '/home/travis/bu...', '/home/travis/bu...') #5 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/config/Loader/DelegatingLoader.php(45): Symfony\Component\Routing\Loader\YamlFileLoader->load('/home/travis/bu...', NULL) #6 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/framework-bundle/Routing/DelegatingLoader.php(76): Symfony\Component\Config\Loader\DelegatingLoader->load('/home/travis/bu...', NULL) #7 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/framework-bundle/Routing/Router.php(54): Symfony\Bundle\FrameworkBundle\Routing\DelegatingLoader->load('/home/travis/bu...', NULL) #8 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/routing/Router.php(373): Symfony\Bundle\FrameworkBundle\Routing\Router->getRouteCollection() #9 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/routing/Router.php(288): Symfony\Component\Routing\Router->getMatcherDumperInstance() #10 [internal function]: Symfony\Component\Routing\Router->Symfony\Component\Routing\{closure}(Object(Symfony\Component\Config\ConfigCache)) #11 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/config/ConfigCacheFactory.php(46): call_user_func(Object(Closure), Object(Symfony\Component\Config\ConfigCache)) #12 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/routing/Router.php(302): Symfony\Component\Config\ConfigCacheFactory->cache('/home/travis/bu...', Object(Closure)) #13 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/routing/Router.php(250): Symfony\Component\Routing\Router->getMatcher() #14 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/http-kernel/EventListener/RouterListener.php(137): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request)) #15 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher)) #16 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(61): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher)) #17 [internal function]: Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) #18 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/event-dispatcher/EventDispatcher.php(164): call_user_func(Object(Symfony\Component\EventDispatcher\Debug\WrappedListener), Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) #19 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/event-dispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #20 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/event-dispatcher/ContainerAwareEventDispatcher.php(167): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #21 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(124): Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #22 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/http-kernel/HttpKernel.php(128): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #23 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #24 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/http-kernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #25 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/http-kernel/Kernel.php(196): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #26 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/http-kernel/Client.php(81): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #27 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/framework-bundle/Client.php(131): Symfony\Component\HttpKernel\Client->doRequest(Object(Symfony\Component\HttpFoundation\Request)) #28 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/browser-kit/Client.php(327): Symfony\Bundle\FrameworkBundle\Client->doRequest(Object(Symfony\Component\HttpFoundation\Request)) #29 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/kleijnweb/swagger-bundle/src/Test/ApiTestCase.php(73): Symfony\Component\BrowserKit\Client->request('GET', '/v2/pet/findByS...') #30 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/src/PetStoreBundle/Tests/PetStoreApiTest.php(34): KleijnWeb\SwaggerBundle\Test\ApiTestCase->get('/v2/pet/findByS...', Array) #31 [internal function]: Acme\PetStoreBundle\Tests\PetStoreApiTest->canFindPetsByStatus() #32 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/phpunit/phpunit/src/Framework/TestCase.php(962): ReflectionMethod->invokeArgs(Object(Acme\PetStoreBundle\Tests\PetStoreApiTest), Array) #33 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/phpunit/phpunit/src/Framework/TestCase.php(826): PHPUnit_Framework_TestCase->runTest() #34 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/phpunit/phpunit/src/Framework/TestResult.php(686): PHPUnit_Framework_TestCase->runBare() #35 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/phpunit/phpunit/src/Framework/TestCase.php(760): PHPUnit_Framework_TestResult->run(Object(Acme\PetStoreBundle\Tests\PetStoreApiTest)) #36 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/phpunit/phpunit/src/Framework/TestSuite.php(699): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult)) #37 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/phpunit/phpunit/src/Framework/TestSuite.php(699): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult)) #38 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(426): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult)) #39 phar:///home/travis/.phpenv/versions/5.6.5/bin/phpunit/phpunit/TextUI/Command.php(152): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array) #40 phar:///home/travis/.phpenv/versions/5.6.5/bin/phpunit/phpunit/TextUI/Command.php(104): PHPUnit_TextUI_Command->run(Array, true) #41 /home/travis/.phpenv/versions/5.6.5/bin/phpunit(722): PHPUnit_TextUI_Command::main() #42 {main}  Next exception 'Symfony\Component\Config\Exception\FileLoaderLoadException' with message 'Document file '../web/petstore.yml' does not exist' in ../web/petstore.yml (which is being imported from "/home/travis/build/kleijnweb/symfony-swagger-microservice-edition/app/config/routing.yml").' in /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/config/Loader/FileLoader.php:130 Stack trace: #0 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/routing/Loader/YamlFileLoader.php(175): Symfony\Component\Config\Loader\FileLoader->import('../web/petstore...', 'swagger', false, '/home/travis/bu...') #1 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/routing/Loader/YamlFileLoader.php(93): Symfony\Component\Routing\Loader\YamlFileLoader->parseImport(Object(Symfony\Component\Routing\RouteCollection), Array, '/home/travis/bu...', '/home/travis/bu...') #2 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/config/Loader/DelegatingLoader.php(45): Symfony\Component\Routing\Loader\YamlFileLoader->load('/home/travis/bu...', NULL) #3 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/framework-bundle/Routing/DelegatingLoader.php(76): Symfony\Component\Config\Loader\DelegatingLoader->load('/home/travis/bu...', NULL) #4 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/framework-bundle/Routing/Router.php(54): Symfony\Bundle\FrameworkBundle\Routing\DelegatingLoader->load('/home/travis/bu...', NULL) #5 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/routing/Router.php(373): Symfony\Bundle\FrameworkBundle\Routing\Router->getRouteCollection() #6 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/routing/Router.php(288): Symfony\Component\Routing\Router->getMatcherDumperInstance() #7 [internal function]: Symfony\Component\Routing\Router->Symfony\Component\Routing\{closure}(Object(Symfony\Component\Config\ConfigCache)) #8 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/config/ConfigCacheFactory.php(46): call_user_func(Object(Closure), Object(Symfony\Component\Config\ConfigCache)) #9 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/routing/Router.php(302): Symfony\Component\Config\ConfigCacheFactory->cache('/home/travis/bu...', Object(Closure)) #10 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/routing/Router.php(250): Symfony\Component\Routing\Router->getMatcher() #11 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/http-kernel/EventListener/RouterListener.php(137): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request)) #12 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher)) #13 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(61): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher)) #14 [internal function]: Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) #15 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/event-dispatcher/EventDispatcher.php(164): call_user_func(Object(Symfony\Component\EventDispatcher\Debug\WrappedListener), Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) #16 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/event-dispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #17 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/event-dispatcher/ContainerAwareEventDispatcher.php(167): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #18 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(124): Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #19 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/http-kernel/HttpKernel.php(128): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #20 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #21 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/http-kernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #22 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/http-kernel/Kernel.php(196): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #23 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/http-kernel/Client.php(81): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #24 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/framework-bundle/Client.php(131): Symfony\Component\HttpKernel\Client->doRequest(Object(Symfony\Component\HttpFoundation\Request)) #25 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/symfony/browser-kit/Client.php(327): Symfony\Bundle\FrameworkBundle\Client->doRequest(Object(Symfony\Component\HttpFoundation\Request)) #26 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/kleijnweb/swagger-bundle/src/Test/ApiTestCase.php(73): Symfony\Component\BrowserKit\Client->request('GET', '/v2/pet/findByS...') #27 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/src/PetStoreBundle/Tests/PetStoreApiTest.php(34): KleijnWeb\SwaggerBundle\Test\ApiTestCase->get('/v2/pet/findByS...', Array) #28 [internal function]: Acme\PetStoreBundle\Tests\PetStoreApiTest->canFindPetsByStatus() #29 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/phpunit/phpunit/src/Framework/TestCase.php(962): ReflectionMethod->invokeArgs(Object(Acme\PetStoreBundle\Tests\PetStoreApiTest), Array) #30 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/phpunit/phpunit/src/Framework/TestCase.php(826): PHPUnit_Framework_TestCase->runTest() #31 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/phpunit/phpunit/src/Framework/TestResult.php(686): PHPUnit_Framework_TestCase->runBare() #32 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/phpunit/phpunit/src/Framework/TestCase.php(760): PHPUnit_Framework_TestResult->run(Object(Acme\PetStoreBundle\Tests\PetStoreApiTest)) #33 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/phpunit/phpunit/src/Framework/TestSuite.php(699): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult)) #34 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/phpunit/phpunit/src/Framework/TestSuite.php(699): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult)) #35 /home/travis/build/kleijnweb/symfony-swagger-microservice-edition/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(426): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult)) #36 phar:///home/travis/.phpenv/versions/5.6.5/bin/phpunit/phpunit/TextUI/Command.php(152): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array) #37 phar:///home/travis/.phpenv/versions/5.6.5/bin/phpunit/phpunit/TextUI/Command.php(104): PHPUnit_TextUI_Command->run(Array, true) #38 /home/travis/.phpenv/versions/5.6.5/bin/phpunit(722): PHPUnit_TextUI_Command::main() #39 {main} [] []
```

**Comment by johnknl** [comment]
No longer happening with latest SwaggerBundle.
